services:

  model-server-empty:
    # Due to the bug MODELIX-606 we need to use an earlier version for the 'fill from MPS use case'
    image: modelix/model-server:3.1.0
    profiles:
      - useCase1
    ports:
      - 28101:28101
    command: ["./run-model-server.sh", "-inmemory"]

  model-server:
    # Keep the version in sync with the modelix version in gradle/libs.versions.toml
    image: modelix/model-server:3.11.0
    profiles:
      - useCase2a
      - useCase2b
      - useCase3
    ports:
      - 28101:28101
    volumes:
      - ./model-server/courses.modelserver.dump:/courses.modelserver.dump
    command: ["./run-model-server.sh", "-inmemory", "-dumpin", "/courses.modelserver.dump"]

  rest-api-model-server:
    image: modelix/rest-api-model-server:latest
    profiles:
      - useCase2a
    ports:
      - 8090:8090
      - 8080:8080

  spa-dashboard-angular:
    image: nginx
    ports:
      - 4200:80
    profiles:
      - useCase2a
      - useCase2b
    volumes:
      - ./spa-dashboard-angular/dist:/usr/share/nginx/html


  spa-overview-angular:
      image: nginx
      profiles:
        - useCase3
      ports:
        - 4200:80
      volumes:
        - ./spa-overview-angular/dist/spa-overview-angular:/usr/share/nginx/html

  spa-management-vue:
    image: nginx
    profiles:
      - useCase3
    ports:
      - 3000:80
    volumes:
      - ./spa-management-vue/dist:/usr/share/nginx/html
