# Before running Nginx, this command writes a
# configuration file suitable for single-page applications.
x-nginx-command: &nginx-command |
  bash -c 'bash -s <<EOF
  cat > /etc/nginx/conf.d/default.conf <<EON
  server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    location / {
       # configure Nginx to work for client side routing
      try_files \\\$$uri \\\$$uri/ /index.html;
    }
  }
  EON
  nginx -g "daemon off;"
  EOF'

services:

  model-server-empty:
    # Keep the version in sync with the modelix version in gradle/libs.versions.toml
    image: modelix/model-server:4.5.0
    container_name: modelix-samples-model-server-empty
    profiles:
      - useCase1
    ports:
      - 28101:28101
    command: ["-inmemory"]

  model-server:
    # Keep the version in sync with the modelix version in gradle/libs.versions.toml
    image: modelix/model-server:4.5.0
    container_name: modelix-samples-model-server
    profiles:
      - useCase2
      - useCase3
      - all
    #      - useCase3b
    ports:
      - 28101:28101
    volumes:
      - ./model-server/courses.modelserver.dump:/courses.modelserver.dump
    command: ["-inmemory", "-dumpin", "/courses.modelserver.dump" ]

  rest-api-model-server:
    image: modelix/rest-api-model-server:latest
    container_name: modelix-samples-rest-api-model-server
    # Needs to be specified, so that container runs in Docker on Mac with ARM
    platform: linux/x86_64
    profiles:
      - useCase3
      - all
    ports:
      # The dashboard expects our service to be running under 8090.
      - 8090:8080
    environment:
      - MODELIX_CLIENT_SERVER_URI=http://model-server:28101

  # This use case is currently being reworked
  #  rest-api-model-ql:
  #    image: modelix/rest-api-model-ql:latest
  #    container_name: rest-api-model-ql
  #    profiles:
  #      - useCase3b
  #    ports:
  #      # The dashboard expects our service to be running under 8090.
  #      - 8090:8080

  spa-dashboard-angular:
    container_name: modelix-samples-spa-dashboard-angular
    image: nginx
    ports:
      - 4201:80
    profiles:
      - useCase3
      - all
    #      - useCase3b
    volumes:
      - ./spa-dashboard-angular/dist:/usr/share/nginx/html
    command: *nginx-command

  spa-overview-angular:
    image: nginx
    container_name: spa-overview-angular
    profiles:
      - useCase2
      - all
    ports:
      - 4200:80
    volumes:
      - ./spa-overview-angular/dist/spa-overview-angular:/usr/share/nginx/html
    command: *nginx-command

  spa-management-vue:
    image: nginx
    container_name: modelix-samples-spa-management-vue
    profiles:
      - useCase2
      - all
    ports:
      - 3000:80
    volumes:
      - ./spa-management-vue/dist:/usr/share/nginx/html
    command: *nginx-command
