global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: # depends on your local deployment and OS
          - modelix-samples-model-server:28101
          - localhost:28101
          - 127.0.0.1:28101 # For connecting to a scrape endpoint from Prometheus running in a Docker container
          - host.docker.internal:28101 # For connecting to a scrape endpoint from Prometheus running in a Docker container

